import Nav from "@/components/nav";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import Footer from "@/components/footer";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  style: ["normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} max-w-[2000px] m-auto bg-neutral-900 relative`}
      >
        <Nav />
        {children}
        <Footer />  
      </body>
    </html>
  );
}
